"""vegetables table

Revision ID: 46321e93fc6f
Revises: ff6c1473b262
Create Date: 2021-02-19 14:22:26.424321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46321e93fc6f'
down_revision = 'ff6c1473b262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vegetables_colour', table_name='vegetables')
    op.drop_index('ix_vegetables_flavour', table_name='vegetables')
    op.drop_index('ix_vegetables_name', table_name='vegetables')
    op.drop_table('vegetables')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vegetables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('colour', sa.VARCHAR(length=120), nullable=True),
    sa.Column('flavour', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vegetables_name', 'vegetables', ['name'], unique=1)
    op.create_index('ix_vegetables_flavour', 'vegetables', ['flavour'], unique=False)
    op.create_index('ix_vegetables_colour', 'vegetables', ['colour'], unique=False)
    # ### end Alembic commands ###
