"""vegetables table

Revision ID: ff6c1473b262
Revises: 56cd79e77dfb
Create Date: 2021-02-19 14:09:09.739216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6c1473b262'
down_revision = '56cd79e77dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vegetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('colour', sa.String(length=120), nullable=True),
    sa.Column('flavour', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vegetables_colour'), 'vegetables', ['colour'], unique=False)
    op.create_index(op.f('ix_vegetables_flavour'), 'vegetables', ['flavour'], unique=False)
    op.create_index(op.f('ix_vegetables_name'), 'vegetables', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vegetables_name'), table_name='vegetables')
    op.drop_index(op.f('ix_vegetables_flavour'), table_name='vegetables')
    op.drop_index(op.f('ix_vegetables_colour'), table_name='vegetables')
    op.drop_table('vegetables')
    # ### end Alembic commands ###
